version: '3.8'

services:
  test-mongodb:
    image: mongo:6.0
    container_name: test_mongo
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  test-api:
    build: .
    container_name: test_api
    environment:
      - MONGO_URI=mongodb://admin:password@test-mongodb:27017/test_db?authSource=admin
      - TESTING=True
    depends_on:
      - test-mongodb
    command: pytest test_app.py -v
    